#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Jared Norman"
email = "jared@super.gd"

[ui]
default-command = "log"
diff-editor = ":builtin"

# Defaults: https://github.com/jj-vcs/jj/blob/main/cli/src/config/colors.toml
[colors]
"rest" = "#cecacd"

"commit_id" = "blue"
"working_copy commit_id" = "blue"

"change_id" = "green"
"working_copy change_id" = "green"

"author" = "#797593"
"working_copy author" = "#797593"

"timestamp" = "#9893a5"
"working_copy timestamp" = "#797593"

"bookmarks" = "yellow"
"working_copy bookmarks" = "yellow"

"description placeholder" = "magenta"
"working_copy description placeholder" = "magenta"

"empty description placeholder" = "#9893a5"
"working_copy empty description placeholder" = "#9893a5"

"empty" = "magenta"
"working_copy empty" = "magenta"
